workspace = { members = ["benchmarks"] }
[package]
name = "musegc"
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"

[dependencies]
ahash = "0.8.11"
crossbeam-utils = "0.8.19"
flume = "0.11.0"
intentional = "0.1.1"
kempt = "0.2.3"
parking_lot = { version = "0.12.1" }

[lints]
clippy.pedantic = "warn"
rust.missing_docs = "warn"

[profile.release]
debug = true
lto = true

[profile.bench]

lto = true
